name: CI
on:
  push:
    branches: [main, master]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Use the full github.com URL for external community actions!
      - uses: https://github.com/julia-actions/setup-julia@v1
        with:
          version: '1.12' # Or your target version
          
      - uses: https://github.com/julia-actions/julia-buildpkg@v1
      - uses: https://github.com/julia-actions/julia-runtest@v1